version: "3.8"
services:
    nginx2:
        container_name: nginx2
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        depends_on:
            - flaskmgpu2
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      
    flaskmgpu2:
        build: ./flaskapp
        container_name: flaskmgpu2
        restart: always
        command: gunicorn -w 1 -b :8000 app:appflask --reload
        environment:
            - FLASK_APP=app
            - FLASK_DEBUG=1
            - PYTHONBUFFERED=True
        volumes:
            - ./flaskapp:/var/www
        ports:
            - "8000:8000"
        
